version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
     - 8040:8080
     - 50000:50000
    container_name: jenkins-ci
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    command: bash -c "groupadd -g 993 docker && gpasswd -a jenkins docker"

  nexus-repo:
    image: sonatype/nexus3:3.41.1
    ports:
      - 8030:8081
      - 5000:5000
    container_name: nexus_repo